services:
  task-fs-mongodb:
    container_name: task-fs-mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin1
    ports:
      - "27017:27017"

  task-fs-mongo-express:
    container_name: task-fs-mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin1
      ME_CONFIG_MONGODB_URL: mongodb://root:admin1@task-fs-mongodb:27017
      ME_CONFIG_BASICAUTH: false
